version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://keyurkns2004:keyur7604@cluster0.hln29kt.mongodb.net/expense-tracker

volumes:
  mongodb_data: 